### ISSUE TITLE
feat: add interchain security (ICS) support to v8 branch

### ISSUE THREAD

**Issue by jtieri** [strangelove-ventures/interchaintest#1041]
The Interchain Security team [recently stated that ICS would support SDK v0.50.x and ibc-go v8.x.x](https://github.com/cosmos/interchain-security/issues/1246#issuecomment-1985847702) which means that we will soon be able to bring support for ICS into the main branch (v8).

**Comment by MSalopek** [comment]
Thank you for the effort! I was not aware of this until I saw a github mention.

This is the latest ICS v5: https://github.com/cosmos/interchain-security/releases/tag/v5.0.0-rc0

The `v5.0.0-rc0` has feature parity with `v4.1.0` (has epochs code).

Can I help you with anything here?

**Comment by Reecepbcups** [comment]
@MSalopek Thanks! It has already been integrated on our side on the latest commit at the time: https://github.com/strangelove-ventures/interchaintest/pull/1088
