### ISSUE TITLE
feature request: ability for chain to specify gentx fee

### ISSUE THREAD

**Issue by rootulp** [strangelove-ventures/interchaintest#1050]
## Context

I'm trying to use `interchaintest` to test ICA for Celestia

## Problem

Celestia recently introduced a [minfee](https://github.com/celestiaorg/celestia-app/blob/main/x/minfee/README.md) module that enforces all transactions specify a minimum transaction fee. Since [these lines](https://github.com/strangelove-ventures/interchaintest/blob/a3f4c7bcccf1925ffa6dc793a298f15497919a38/chain/cosmos/chain_node.go#L743-L745) don't specify a fee, we're hitting:

```
    ica_test.go:59:
        	Error Trace:	/Users/rootulp/git/rootulp/celestiaorg/celestia-app/test/interchain/ica_test.go:59
        	Error:      	Received unexpected error:
        	            	failed to start chains: failed to start chain celestia-1: All attempts fail:
```

```
        	Test:       	TestICA
    setup.go:148: Container logs - {/celestia-val-0-TestICA}
        /                    "mode": "SIGN_MODE_DIRECT"
                          }
                        },
                         "sequence": "0"
                      }
                    ],
                    "fee": {
                      "amount": [],
        %              "gas_limit": "210000",
                      "payer": "",
                      "granter": ""
                    },
                    "tip": null
          },
                  "signatures": [
        g            "ozMn+hlCwk3uyCOiHo2/cu8yp53KtKc4LzDcZY9pyBAOkbIQLFqRgjCe9sWt+qTVH3Fjyg6PYzaIUrtwxJMWJw=="

                  ]
        w        }': insufficient gas price for the network; got: 0 required at least: 420.000000000000000000: insufficient fee

```

## Proposal

Allow a chain to specify a fee for the gentx command. For example, something like [this](https://github.com/celestiaorg/celestia-app/commit/eba62c9a7198984b80c46c71718b8e529cd6b9c2) should resolve. 

Note we're on ibc-go v6 so we're using interchaintest v6. I realize that's no longer supported so if this can't be addressed upstream, we can create a fork.

**Comment by Reecepbcups** [comment]
@rootulp Celestia want's a fee on a gentx? That's a really odd case for the base module spec vs just skipping block 1 fee check. 

It can be supported easily but bad UX imo on the celestia side. x/GlobalFee from cosmoshub for example does this same thing yet does not require fees on block 0/1

**Comment by Reecepbcups** [comment]
re: v6. We will support for v7 / main v8, but a PR can be made to add support to previous versions we no longer maintain.

**Comment by rootulp** [comment]
Agreed, it does seem odd. TBH I think this is an unintended side-effect of our `x/minfee` implementation so I think we should explore skipping required fees for the first block. Thanks for the feedback and speedy review!
