### ISSUE TITLE
icad error on unknown data type

### ISSUE THREAD

**Issue by rootulp** [strangelove-ventures/interchaintest#1057]
## Context

I'm trying to test ICA on Celestia using interchaintest. When I use the counterparty chain ICAD (I think Inter-Chain Accounts Demo) then I encounter an error.

## Problem

```
        �2024-04-08T02:47:34.307232Z	error	Error sending messages	{"path_name": "path", "src_chain_id": "icad-2", "dst_chain_id": "celestia", "src_client_id": "07-tendermint-0", "dst_client_id": "07-tendermint-0", "error": "rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 1: channel open try callback failed for port ID: icahost, channel ID: channel-1: cannot unmarshal ICS-27 interchain accounts metadata: unknown data type [cosmos/ibc-go/v6@v6.2.1/modules/apps/27-interchain-accounts/host/keeper/handshake.go:39] With gas wanted: '18446744073709551615' and gas used: '143127' : unknown request"}
```

I noticed the [icad Docker image](https://github.com/cosmos/interchain-accounts-demo/pkgs/container/ibc-go-icad) is deprecated but it's the only one I could get to start successfully. I'd rather use Stride or Cosmos Hub but I hit other issues with them. I'm using [this](https://gist.github.com/Reecepbcups/8ec46ad83f6c9c1a152c10ab25774335#file-interchain_accounts_test-go-L44) for inspiration.

**Comment by jtieri** [comment]
Yeah there have been some substantial changes to interchain accounts since the example test was written, I don't know if the ICAD binary is going to be a viable option anymore. 

Can you elaborate on what type of issues you hit while trying to use the Cosmos Hub?

**Comment by rootulp** [comment]
Sure! Let's close this one as "won't do" because I agree the ICAD image seems no longer supported.

The Cosmos Hub issue is in https://github.com/strangelove-ventures/interchaintest/issues/1055 so can add more details there.
