### ISSUE TITLE
Integrate Interchaintest w/ Onex

### ISSUE THREAD

**Issue by jonathanpberger** [strangelove-ventures/interchaintest#1062]

**Comment by joelsmith-2019** [comment]
Working on integrating interchaintest with Onex. So far we have a working consumer chain (onomy) and provider chain (onex), but the relayer is not 100% setup for relaying the CCV packets. Working with the Onomy team / validator set to resolve the issue.

**Comment by joelsmith-2019** [comment]
Waiting on Onomy team to update Onomy to sdk v0.47 and Onex to sdk v0.50

**Comment by Reecepbcups** [comment]
@joelsmith-2019 this is unblocked as of v8.3.0 with ICS support for SDK v50 chains :) (Onomy is the provider right? if so it needs to be v4.1.0 ICS at the moment. Current relayer is not picking up packets on v4.2.0+ ICS providers).  Works with hermes. ref: https://github.com/rollchains/spawn/pull/136/files (v50 consumer + 47 provider)

**Comment by jonathanpberger** [comment]
@joelsmith-2019 reached out, we're still waiting for them to update.

**Comment by jtieri** [comment]
> This

if i'm not mistaken the Onomy community has decided to spin down Onex? maybe i'm wrong but if that is the case then we can safely close this ticket out and revisit Onomy integration when the team requests it
