### ISSUE TITLE
`HostPortOverride` does not support use with full nodes

### ISSUE THREAD

**Issue by pirtleshell** [strangelove-ventures/interchaintest#1089]
Note: This issue only focuses on cosmos chain nodes.

# Overview

When `HostPortOverride` is set in the chain config, the chain must be run with no full nodes. Additionally, the port(s) are only exposed on the first validator node.

Because only one process can bind to a single host port, the explicit port exposures defined in `HostPortOverride` are only applied to the first validator. This is enforced by only applying the override to nodes with `Index == 0`:

https://github.com/strangelove-ventures/interchaintest/blob/c8b741617cd8da95d4377c938c411c452490d16f/chain/cosmos/chain_node.go#L1062-L1072

However, because `cosmosChain.Validators[0].Index` and `cosmosChain.FullNodes[0].Index` are both `0`, a chain with port overrides will not start when `NumFullNodes` > 0 (the 0th full node and 0th validator cannot both bind to the override port).

## Reproduction
Attempt to start a chain with non-empty `HostPortOverride` map and at least one Full Node:
```go
one := 1
cf := interchaintest.NewBuiltinChainFactory(zaptest.NewLogger(t), []*interchaintest.ChainSpec{
	{
		Name:    "gaia",
		Version: "v15.2.0",
		ChainConfig: ibc.ChainConfig{
			HostPortOverride: map[int]int{8080: 8080}, // <--- attempting to expose port 8080
		},
		NumFullNodes: &one, // <--- default value, one full node alongside the validators
	},
})
```
Error: `failed to start chain gaia-2: failed to generate port bindings: listen tcp 127.0.0.1:8080: bind: address already in use`

Note that the port binding conflict is from starting the validator with port 8080 exposed, and then attempting to start the full node with port 8080 exposed. It isn't from an already-running process bound to port 8080 😄 

## Current Workaround

The current workaround for the above problem is to only run validator nodes (no full nodes) by setting `NumFullNodes` to zero. When there are no full nodes, there are not conflicts in the bound ports of the chain nodes so the chain starts without problem.

# Proposed Solution

## Simple Fix

To allow Full nodes to run alongside validators while still allowing the first validator to have custom (explicit) port(s) exposed, update the existing condition to check that the node is a validator in addition to having `Index == 0`:
```
tn.Validator && tn.Index == 0 && chainCfg.HostPortOverride != nil
```

This should be backwards compatible because:
1. a chain must have a validator to run
2. no current implementation using the `HostPortOverride` map works with full nodes & a validator

I've opened a PR with this change: https://github.com/strangelove-ventures/interchaintest/pull/1090

## Improved DevX

Leverage the currently used random host port assignment for user-defined ports by adding a config value that is a list of port ids that look like `<port>/<protocol>`. This, coupled with a new utility function for finding host addresses by port id would allow exposing arbitrary ports on _all_ nodes (multiple validators & full nodes).

This can be implemented by injecting the user-defined port ids into the `usingPorts` map here: https://github.com/strangelove-ventures/interchaintest/blob/c8b741617cd8da95d4377c938c411c452490d16f/chain/cosmos/chain_node.go#L1057

Example: Ethermint chains run Ethereum JSON-RPC APIs on port 8545. This port could be exposed, and the endpoint used, by adding a new config property & a helper func to get the host address:
```go
chainConfig := ibc.ChainConfig{
	// chain config details here...
	ExposeAdditionalPorts: []string{"8545/tcp"}
}
// ...
// get address for the exposed ports on a node
fullNode0EvmUrl := chain.FullNodes[0].GetHostAddress(ctx, "8545/tcp")
validator0EvmUrl := chain.Validators[0].GetHostAddress(ctx, "8545/tcp")
```

The benefit of a new implementation like this is that we can expose ports on all validators and full nodes, instead of only the first validator.

Let me know if this should be a separate feature request ticket---I'd be happy to create it.

**Comment by Reecepbcups** [comment]
@pirtleshell  Thanks! The improved Dev UX should be in its own PR since it's a feat rather than a fix.

**Comment by pirtleshell** [comment]
thanks @Reecepbcups. sounds good, i will open a feature request ticket

**Comment by pirtleshell** [comment]
opened an issue referencing the feature request here.

thanks for the fast merge @Reecepbcups 🎉 appreciate this great testing framework y'all have going here 🙏
