### ISSUE TITLE
[Bug]: Unexpected behavior in the StakingQueryDelegationsTo function

### ISSUE THREAD

**Issue by LucaPalla95** [strangelove-ventures/interchaintest#1261]
### What happened and what did you expect to happen?

I was using the StakingQueryDelegationsTo function to verify whether the delegations I made in previous steps were successfully recorded. Specifically, I had a situation where I staked a certain amount of tokens (Y) to validator X via self-bonding, and I also staked a smaller portion using a different account (custom delegator).
What I expected as output were two different delegations: one for the validator itself and one for the custom user (delegator). However, what I received instead were two rows containing the same information.
![Image](https://github.com/user-attachments/assets/86771a05-e4fe-41a7-8def-4e12919ca75c)
I expected to receive something like:
![Image](https://github.com/user-attachments/assets/6df34586-d4ef-40b6-8fa1-1066e17e317f)

### Describe how to reproduce the bug

I tried reproducing the bug multiple times by staking with different users and querying for delegations, and the bug was always present. I tried also different chains configurations.

### version

Latest Version

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Reecepbcups** [comment]
resolved in above PRs, thanks !
