### ISSUE TITLE
Interchaintest should have tests for timeouts on ordered channels.

### ISSUE THREAD

**Issue by agouin** [strangelove-ventures/interchaintest#14]
Currently have tests to cover unordered with and without both height timeout and timestamp timeout.
See #5 and #12 

Need to add tests for timeouts on ordered channels.
Some context here https://github.com/cosmos/relayer/issues/321

More context from @jtieri:
Timeouts on ordered channels work a little different than unordered timeouts because in ordered channels packets must be processed in FIFO order so if a packet with sequence 2 times out then every packet with sequence n > 2 cannot be processed. What happens in ordered channels is if a packet times out the channel is closed
In the relayer we don't currently differentiate between the two, ordered channels require a proof of nextpacketrecv and unorderd channels require a proof of non existence to prove they have not been relayed

**Comment by agouin** [comment]
From backend sprint planning: larger piece of work but would like to bring interchain accounts tests into conformance suite and add ChainCapability for interchain accounts, marking specific chains that support it.

**Comment by Reecepbcups** [comment]
Handled in the relayer, will link to those test from ICT in a future PR
