### ISSUE TITLE
Configuration should be less confusing.

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/interchaintest#151]
## Problem

 I know we've sunk a lot of time into this already, but I still think configuration is confusing. 

See https://github.com/DavidNix/ibc-go/pull/1 as an example. I gave this PR to the ibc-go team to help them integrate ibctest into their CICD. 

Namely:

```
cf := ibctest.NewBuiltinChainFactory(logger, []*ibctest.ChainSpec{
 		{Name: "gaia", ChainConfig: setup.NewSimappConfig("simapp-a", "chain-a", "atoma")},
 		{Name: "gaia", ChainConfig: setup.NewSimappConfig("simapp-b", "chain-b", "atomb")},
 	})
```

`ChainSpec` and `ChainConfig` duplicate a lot of the same fields like Name, GasAdjustment, NoHostMount, etc. 

In the above they want to test a simapp. I feel there should be a more obvious way to hand over a complete ChainConfig or select a default one we provide, perhaps with optional builder methods to override. 

I'm also wondering if we can use the `Interchain` here as well and perhaps even forgo factories entirely. (That's a large hypothesis though).

**Comment by jtieri** [comment]
I got a custom chain configured using a local docker image and the chains seem to spin up properly with no errors. I agree it's not the most straightforward setup though and there seems to be issues if you try to configure a chain with the denom `stake`

https://github.com/strangelove-ventures/ibctest/blob/894619c9255d36d6b9055d7edd24d9f38794da14/icq_test.go#L24-L55

**Comment by boojamya** [comment]
> there seems to be issues if you try to configure a chain with the denom `stake`

When the "interchain" is `built`, each validator is funded with "stake" denom during genesis. This may be the reason for this denom issue.

**Comment by jonathanpberger** [comment]
Iceboxing for now, but feel free to close this as stale if it's no longer worth doing. cc @DavidNix
