### ISSUE TITLE
Fee middleware should have assertions.

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/interchaintest#154]
See https://github.com/cosmos/ibc-go/issues/396 for ibc-go's manual QA test plan.

As of this writing, this story is likely blocked because:
* Still in active development for ibc-go.
* cosmos/relayer support

**Comment by DavidNix** [comment]
We may need to expose ways to get the relayer address. 

Per ibc-go team:
>  I wanted to to do some assertions on relayer accounts. I didn't see a way of getting the relayer addresses. We're working on packet incentivization which requires registering a relayer address on the counter party chain.

**Comment by Reecepbcups** [comment]
No one uses the Fee Module, does not make sense to add verifications for despite being in prod for over a year now. no adoption or UIs. At least 2 years out
