### ISSUE TITLE
Interchaintest should have a test for multi-hop.

### ISSUE THREAD

**Issue by agouin** [strangelove-ventures/interchaintest#16]
https://github.com/cosmos/ibc/issues/548

**Comment by boojamya** [comment]
Linking: https://github.com/strangelove-ventures/ibctest/pull/306

**Comment by jonathanpberger** [comment]
The relayer side has been picked up by Polymer:

https://github.com/cosmos/relayer/compare/main...polymerdao:relayer:giuseppe/multihop

Once that work is complete (they said "will drop PR next week"), this story will be unblocked and we can add the test coverage to InterchainTest

**Comment by Reecepbcups** [comment]
Sounds like they stopped work on this or is no longer being added to our relayer. Given the time, counting as stale. We can add back in once something tangible can be done.
