### ISSUE TITLE
Expose user private keys

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/interchaintest#172]
Feedback from ibc-go team:

>  I'm trying to add a test which creates an signs a transaction using a grpc client. In order to do this I need the private key of a user. Can you think of a relatively straight forward way of doing this?

> I see that the generated private keys go into some db somewhere? But maybe we could use a preset fixture of a mnemonic/public/private key for certain tests that need access to this. What do you think?

**Comment by chatton** [comment]
To add some specifics, I was following [these docs](https://docs.cosmos.network/master/run-node/txs.html#generating-a-transaction-2) and was unable to sign the transaction on behalf of a created user as we cannot access the private keys.

**Comment by chatton** [comment]
It looks like we should be able to [derive the private key from a mnemonic](https://github.com/cosmos/cosmos-sdk/blob/55054282d2df794d9a5fe2599ea25473379ebc3d/x/genutil/utils.go#L86). 

Maybe if we instead `--restore` users when adding them, we could return the private key as a new field on [this struct](https://github.com/strangelove-ventures/ibctest/blob/df20bc5611d19a8a07d03363ca1cc13bb9c2a32e/test_user.go#L15)

**Comment by jonathanpberger** [comment]
Closing as stale.
