### ISSUE TITLE
Feature Request: Add functionality to wait for events

### ISSUE THREAD

**Issue by chatton** [strangelove-ventures/interchaintest#184]
Currently we have functionality to wait for a number of blocks as a mechanism to account for delay of certain operations to be seen by the test.

It would be useful to be able to listen for events and wait specific ones to be emitted.

```golang
// incentivise packet 

err := events.WaitFor(chainA, feetypes.EventTypeIncentivizedPacket, timeOut)
require.NoError(t, err)

// continue with test

```

**Comment by jonathanpberger** [comment]
This is now possible with the `BlockPoller`. See here for an example:

https://github.com/strangelove-ventures/interchaintest/blob/cc5bb34eeea5c54164eb361b595b754df037590a/testutil/poll_for_state.go#L63
