### ISSUE TITLE
Add tests for submit misbehavior

### ISSUE THREAD

**Issue by agouin** [strangelove-ventures/interchaintest#20]
https://github.com/cosmos/ibc/blob/master/spec/client/ics-007-tendermint-client/README.md#misbehaviour

Test that the light clients are frozen when relayers submit misbehavior, for a situation such as if two headers could be considered valid for the same height

**Comment by jonathanpberger** [comment]
Test exists in Relayer (https://github.com/cosmos/relayer/pull/1121), closing ticket.
