### ISSUE TITLE
Add a default timeout to use when sending packets for CosmosChain

### ISSUE THREAD

**Issue by colin-axner** [strangelove-ventures/interchaintest#240]
Add a function `GetTimeout()` to `CosmosChain` which returns a valid timeout which is not expected to timeout before the packet is relayed. This will be useful when test writers write tests which require sending packets that must specify timeouts. It is probably easier to specify the timeout height rather than the timeout timestamp

**Comment by agouin** [comment]
You can pass `nil` for `timeout` to `SendIBCTransfer` to use the default timeout for cosmos chains. Do you see an additional need for this method?

**Comment by colin-axner** [comment]
We've been using `BroadcastMessages` and thus constructing our own Msg's. Each Msg which results in an IBC packet being sent will require setting a timeout

We have added this function to our own codebase, so I'm fine closing if you'd prefer not to add the additional code
