### ISSUE TITLE
Rename CosmosChain to Chain

### ISSUE THREAD

**Issue by colin-axner** [strangelove-ventures/interchaintest#241]
The package that contains `CosmosChain` is named `cosmos`, thus the import stutters `cosmos.CosmosChain`. Renaming to `Chain` would result in `cosmos.Chain`

**Comment by jonathanpberger** [comment]
Decided we weren't gonna do this because even though it stutters, searching the repo for `CosmosChain` makes it easier to find what you're looking for. Closing ticket.
