### ISSUE TITLE
Non-core `Chain` functions should be moved to separate packages.

### ISSUE THREAD

**Issue by jtieri** [strangelove-ventures/interchaintest#256]
@chatton had a good idea of bundling non-core `Chain` functions to more domain specific packages that could be used to provide easy to use functions for new IBC related features once they have move out of the in-development phase and their API's are generally finalized.

See: https://github.com/strangelove-ventures/ibctest/issues/236#issuecomment-1211699805

This would allow us to keep the `Chain` interface minimal while still providing easy to use functions for features that have matured past the point of early development. 

The idea is to expose an interface like this
```
type Execer interface {
  Exec(ctx context.Context, cmd []string, env []string) (stdout, stderr []byte, err error)
}
```

which could then be used to expose functions for domain specific use cases like the following

```
package ibctestica

func RegisterAccount(execer Execer, params...) (string, error) {
  execer.Exec(...)
}

// ibctestica.RegisterAccount(chainA, params...)
```

**Comment by jonathanpberger** [comment]
Closing as stale (unloved?). Will reinstantiate if asked for it again.
