### ISSUE TITLE
All chains from Chain-Reg should be added to the test matrix.

### ISSUE THREAD

**Issue by boojamya** [strangelove-ventures/interchaintest#27]
- [ ] `bitcanna`
- [ ] `cosmoshub`
- [ ] `firmachain`
- [ ] `likecoin`
- [ ] `persistence`
- [ ] `stargaze`
- [ ] `bitsong`
- [ ] `cronos`
- [ ] `gravitybridge`
- [ ] `lumnetwork`
- [ ] `provenance`
- [ ] `starname`
- [ ] `bostrom`
- [ ] `cryptoorgchain`
- [ ] `impacthub`
- [ ] `microtick`
- [ ] `regen`
- [ ] `terra`
- [ ] `agoric`
- [ ] `carbon`
- [ ] `decentr`
- [ ] `injective`
- [ ] `nomic`
- [ ] `rizon`
- [ ] `akash`
- [ ] `cerberus`
- [ ] `desmos`
- [ ] `irisnet`
- [ ] `odin`
- [ ] `secretnetwork`
- [ ] `thorchain`
- [ ] `arkh`
- [ ] `dig`
- [ ] `juno`
- [ ] `oraichain`
- [ ] `sentinel`
- [ ] `umee`
- [ ] `cheqd`
- [ ] `emoney`
- [ ] `kava`
- [ ] `osmosis`
- [ ] `shentu`
- [ ] `vidulum`
- [ ] `axelar`
- [ ] `chihuahua`
- [ ] `evmos`
- [ ] `kichain`
- [ ] `panacea`
- [ ] `sifchain`
- [ ] `bandchain`
- [ ] `comdex`
- [ ] `fetchhub`
- [ ] `konstellation`
- [ ] `sommelier`

**Comment by jonathanpberger** [comment]
Blocked on https://github.com/strangelove-ventures/interchaintest/issues/407

**Comment by boojamya** [comment]
This should be merged first: https://github.com/strangelove-ventures/interchaintest/pull/399

**Comment by jonathanpberger** [comment]
Test seems to have a race condition. :-(
