### ISSUE TITLE
Hermes support

### ISSUE THREAD

**Issue by adizere** [strangelove-ventures/interchaintest#3]
Great initiative with the work here, love it!

I just wanted to quickly drop a couple of resources here detailing our current process of automatically creating docker images with every release of Hermes. Hoping these hints could help understanding how to support Hermes in the testing framework.

- Docker tags uploaded here: https://hub.docker.com/r/informalsystems/hermes/tags
- Images are based on this docker file: https://github.com/informalsystems/ibc-rs/blob/master/ci/hermes.Dockerfile

**Comment by mark-rushakoff** [comment]
I took a look at this for a bit today. It should be pretty straightforward to extract a basic DockerRelayer interface and then let both the rly and hermes implementations provide a simple, narrow interface to provide the right commands to the containers, and add a small amount of configuration where appropriate.

**Comment by adizere** [comment]
cc @seanchen1991 and @charleenfei
