### ISSUE TITLE
Upgrade tests against present branch

### ISSUE THREAD

**Issue by faddat** [strangelove-ventures/interchaintest#353]
## note

Please assume that I am referencing the examples folder in the v3 branch of ibctest.

## Goal

In github actions, test an upgrade from Juno v11 to Juno v12, before the v12 release has been tagged

## Problems

* we end up with another go.mod file
* IBCTest is looking up juno versions presumably in the chain registry
* tying this into CI has never been done before
* unlikely to be possible with standard ci (github actions)
* requires tagged releases

**Comment by jtieri** [comment]
> * we end up with another go.mod file

You mean in the Juno repo? I'm presuming you mean something like [this](https://github.com/cosmos/relayer/tree/main/ibctest)

That could possibly be avoided if the main package for the repo is using same dep versions as the version of `ibctest` you are using. Regardless I don't see why this is necessarily a problem, Go modules as a dependency management system are incredibly simple and straightforward and do not add much overhead/technical debt.

> * IBCTest is looking up juno versions presumably in the chain registry

By default `ibctest` will attempt to look for the Docker images in [heighliner](https://github.com/orgs/strangelove-ventures/packages?repo_name=heighliner) but you can point to to whatever repo you want where the Docker image is built and the versioning/tags can be whatever you want them to be.

> * tying this into CI has never been done before
> * unlikely to be possible with standard ci (github actions)

We run a CI job in the relayer for `ibctest` and I believe the ibc-go team is also using `ibctest` in their CI. You are essentially just running standard Go tests so there is a lot of flexibility as far as how you could run the tests in CI.

https://github.com/cosmos/relayer/blob/main/.github/workflows/ibctest.yml
https://github.com/cosmos/ibc-go/search?q=ibctest

> * requires tagged releases

You don't need tagged releases of the chain binaries, you need tagged Docker images that can be pulled from some repository. That means you can build the Docker images from any arbitrary branch or codebase and push to a remote Docker repo like GHCR and you are up and running. It's possible that you could build the Docker images in CI and pipe the image information into the test cases and the CI job for running the test but I'm not 100% sure what that would look like 

There is already an example showing how a test case for upgrading Juno would look like [here](https://github.com/strangelove-ventures/ibctest/blob/main/examples/cosmos/chain_upgrade_test.go)

**Comment by Reecepbcups** [comment]
Dan's documentation work has made this more available now as seen here
https://github.com/strangelove-ventures/interchaintest/blob/main/docs/writeCustomTests.md

Closing since this + Juno, Noble, and PersistanceOne show how to do this in prod.
