### ISSUE TITLE
Test case for ICA should not fail when using the latest tagged Docker release.

### ISSUE THREAD

**Issue by jtieri** [strangelove-ventures/interchaintest#367]
The interchain accounts demo was failing due to us using the `latest` tag which must have introduced some breaking change. For now I reverted to `v0.3.5` but we will want to look into this and adjust things as necessary.

**Comment by chatton** [comment]
I believe the ICA tests here use the `intertx` command which was deprecated. [here](https://github.com/cosmos/ibc-go/blob/b69b8276d77e7b37633ad99643ef1912ec8f8175/e2e/tests/interchain_accounts/base_test.go#L55) is an example of a recent ICA test which should be similar to what you need for your test!

**Comment by Reecepbcups** [comment]
This was moved out of the repo and put upstream in IBC-Apps. No longer applies to interchaintest :D
