### ISSUE TITLE
Smart contract developer should have a CosmWasm build flow which allows easy re-running w/o manual steps.

### ISSUE THREAD

**Issue by agouin** [strangelove-ventures/interchaintest#370]
It is currently possible to store, instantiate, and execute wasm smart contracts on a `CosmosChain` with the `StoreContract`, `InstantiateContract`, and `ExecuteContract` methods. `StoreContract` requires a `fileName` to a compiled wasm binary in order to upload the contract to the chain.

To enable a smart contract developer flow, it would be great to have a method to compile wasm contract source code so that the developer could modify the smart contract and re-run the test case without having to manually re-compile the binary and copy/move it to the correct path in between.

This will also allow contract source code to be committed with the test cases instead of compiled binaries.

example:

```golang
func (c *CosmosChain) CompileContract(
  workingDirectory string, // working directory of the smart contract project on local machine
  buildCommand string, // command to run to compile binary e.g. `cargo wasm`
  binaryPath string, // relative path to compiled binary within working directory inside docker container
  outputPath string, // path to store binary on local machine
) error {
  // launch docker container from a wasm build docker image

  // copy `workingDirectory` contents from
  // local machine to build folder inside container

  // execute `buildCommand`

  // use programmatic docker copy to copy compiled binary 
  // from `binaryPath` inside the container to `outputPath` on local machine

  return nil
}
```

**Comment by boojamya** [comment]
Related: https://github.com/strangelove-ventures/interchaintest/issues/424
