### ISSUE TITLE
Concurrently running test cases should not be flaky when using interchain security.

### ISSUE THREAD

**Issue by jtieri** [strangelove-ventures/interchaintest#395]
When running multiple test cases in parallel that utilize interchain security there seems to be some flakiness around the initialization of the provider and consumer chains. Sometimes initialization completely fails, see logs below, and sometimes the channel creation takes so long that you effectively need to wait for 10-20 blocks before you can make any assertions around things like channel state or the ability to relay ibc packets.

Logs:
```
Error:          Received unexpected error:
                failed to start chains: failed to start provider chain gaia-7: proposal status did not change to passed in expected number of blocks: proposal status (PROPOSAL_STATUS_REJECTED) does not match expected: (PROPOSAL_STATUS_PASSED)
Test:           TestIBCSwapMiddleware_FailRefund
```

**Comment by Reecepbcups** [comment]
I do not think this is an issue in the v7 branch anymore, should be the same for v8.

**Comment by Reecepbcups** [comment]
no longer an issue
