### ISSUE TITLE
Interchaintest should have an option to "Keep Environment Alive After Test Completion".

### ISSUE THREAD

**Issue by boojamya** [strangelove-ventures/interchaintest#400]
Currently, after a test has run, `interchaintest` closes down all docker containers taking down the testnet. 

There should be an option to keep the environment alive to allow exploration of nodes.

**Comment by chatton** [comment]
This would be a great addition! I wonder if [this mechanism](https://github.com/strangelove-ventures/interchaintest/blob/5ad0cec216e712fd3832ca2e65fc7a5cc1b45b8f/test_setup.go#L23-L31) could be expanded to allow for it?
