### ISSUE TITLE
Intermittent failures occur during chain startup

### ISSUE THREAD

**Issue by chatton** [strangelove-ventures/interchaintest#402]
We periodically notice startup errors in our tests when spinning up the chain containers. For example [this](https://github.com/cosmos/ibc-go/actions/runs/3530940914/jobs/5923576191) one.

The errors look like

```
Error:      	Received unexpected error:
        	            	failed to start chains: failed to start chain simapp-b: All attempts fail:
        	            	#1: post failed: Post "http://localhost:49162": read tcp [::1]:43896->[::1]:49162: read: connection reset by peer
        	            	#2: post failed: Post "http://localhost:49162": read tcp [::1]:46596->[::1]:49162: read: connection reset by peer
        	            	#3: post failed: Post "http://localhost:49162": EOF
        	            	#4: post failed: Post "http://localhost:49162": read tcp [::1]:46618->[::1]:49162: read: connection reset by peer
        	            	#5: post failed: Post "http://localhost:49162": read tcp [::1]:50548->[::1]:49162: read: connection reset by peer
        	            	#6: post failed: Post "http://localhost:49162": read tcp [::1]:50550->[::1]:49162: read: connection reset by peer
        	            	#7: post failed: Post "http://localhost:49162": EOF
        	            	#8: post failed: Post "http://localhost:49162": EOF
        	            	#9: post failed: Post "http://localhost:49162": read tcp [::1]:58102->[::1]:49162: read: connection reset by peer
        	            	#10: post failed: Post "http://localhost:49162": read tcp [::1]:58116->[::1]:49162: read: connection reset by peer
        	            	#11: post failed: Post "http://localhost:49162": EOF
        	            	#12: post failed: Post "http://localhost:49162": read tcp [::1]:48660->[::1]:49162: read: connection reset by peer
        	            	#13: post failed: Post "http://localhost:49162": read tcp [::1]:48672->[::1]:49162: read: connection reset 
```

In most cases, they will succeed after a retry.

Briefly looking into the code, it looks like something is going wrong [here](https://github.com/strangelove-ventures/interchaintest/blob/0b3a8a07775d19fe06ae3f2c0ed5023faae93464/chain/cosmos/chain_node.go#L964-L967). It's difficult to tell if the containers would succeed after some more time, or if they would need to be re-created from scratch.

The retry polls over 2 minutes which seems like a reasonable time, but something is getting stuck somewhere.

I wonder would be it worth attempting a removal / re-creation of the container before returning the error.

Because we run 1 host per test, the docker setup code executes very frequently and we see around 3-5% of tests can run into this issue.

**Comment by colin-axner** [comment]
See my comment [here](https://github.com/cosmos/ibc-go/issues/2827#issuecomment-1466003623), I also opened an issue on [cometbft](https://github.com/cometbft/cometbft/issues/516) to look into this further. 

Does anyone have any potential ideas?
