### ISSUE TITLE
Add dependabot support

### ISSUE THREAD

**Issue by colin-axner** [strangelove-ventures/interchaintest#421]
Add dependabot to at least be alerted that newer versions of dependencies are available even if one chooses not to update to that dependency. I noticed when we added dependabot to our `e2e` module, there were a few dependencies that would need to be updated here first, like [docker](https://github.com/cosmos/ibc-go/pull/3269)

Here's the ibc-go [dependabot file](https://github.com/cosmos/ibc-go/blob/main/.github/dependabot.yml)

**Comment by boojamya** [comment]
Oh Dependabot.
Done!
