### ISSUE TITLE
Conformence tests should be well-documented.

### ISSUE THREAD

**Issue by jonathanpberger** [strangelove-ventures/interchaintest#446]
As interchaintest as a library user
I want to be able to discover the conformance package 
Because its [the standard way](https://en.wikipedia.org/wiki/Convention_over_configuration) to test my ibc integration

### Acceptance Criteria
- [x] a link from the interchaintest `README`
- [x] a .md file w/in docs explaining how to use conformance from the interchaintest binary
- [x] a .md file w/in docs explaining how to use conformance as a library

**Comment by jtieri** [comment]
I have just opened a PR that will add a doc to `interchaintest` explaining how to import into other repos as a library to make use of the `conformance` testing suite [here](https://github.com/strangelove-ventures/interchaintest/pull/855)
