### ISSUE TITLE
interchaintest should be integrated into Cosmos SDK

### ISSUE THREAD

**Issue by jonathanpberger** [strangelove-ventures/interchaintest#459]
Integrate interchaintest and articulate a canonical e2e testing framework and strategy in coordination with efforts to establish an integration testing framework.

**Comment by jonathanpberger** [comment]
@mark-rushakoff this ticket is meant to represent the intechaintest <=> SDK work specified in the ICF grant. HMW best represent this in the backlog? Let's chat in this thread (or hmu in slack or something if you wanna talk synchronously).

**Comment by mark-rushakoff** [comment]
I'm currently working on filling in another level of testing between integration tests and e2e tests for the SDK, where we instantiate multiple instances of an app running with Comet, in-process. That is the more urgent SDK need, which we can spread out to SDK consumers as well.

Following that, the best fit for interchaintest in the SDK would be to cover upgrade testing where we cannot realistically have two versions of an app with different SDK version dependencies, in process.
