### ISSUE TITLE
Weird bug when creating channels

### ISSUE THREAD

**Issue by Art3miX** [strangelove-ventures/interchaintest#461]
Context can be found in: #424 
We are trying to open a channel between 2 contracts:

```go
err = relayer.CreateChannel(ctx, erp, ibcPath, ibc.CreateChannelOptions{
    SourcePortName: leftPort,
    DestPortName:   rightPort,
    Order:          ibc.Unordered,
    Version:        "counter-1",
})

err = testutil.WaitForBlocks(ctx, 10, left, right)
```

Right after that we are trying to call `GetChannels` to get the data of the channels:
```go
leftChannelInfo, err := relayer.GetChannels(ctx, erp, left.Config().ChainID)
rightChannelInfo, err = relayer.GetChannels(ctx, erp, right.Config().ChainID)
```

But the result we get are weird and doesn't make sense.
Here is the result of the left chain, which does make sense, 2 channels are open, the transfer channel, and between our contracts:
```go
left channel info: [
  {State:STATE_OPEN Ordering:ORDER_UNORDERED Counterparty:{PortID:transfer ChannelID:channel-0} ConnectionHops:[connection-0] Version:ics20-1 PortID:transfer ChannelID:channel-0}
  {State:STATE_OPEN Ordering:ORDER_UNORDERED Counterparty:{PortID:wasm.juno1suhgf5svhu4usrurvxzlgn54ksxmn8gljarjtxqnapv8kjnp4nrsf8smqw ChannelID:channel-1} ConnectionHops:[connection-0] Version:counter-1 PortID:wasm.juno14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9skjuwg8 ChannelID:channel-1}
]
```
so `channel-0 <=> channel-0` and `channel-1 <=> channel-1`, which is correct.

But looking at the right chain (2nd chain), we introduced with a new channel in TRYOPEN state:
```go
right channel info: [
  {State:STATE_OPEN Ordering:ORDER_UNORDERED Counterparty:{PortID:transfer ChannelID:channel-0} ConnectionHops:[connection-0] Version:ics20-1 PortID:transfer ChannelID:channel-0} 
  {State:STATE_OPEN Ordering:ORDER_UNORDERED Counterparty:{PortID:wasm.juno14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9skjuwg8 ChannelID:channel-1} ConnectionHops:[connection-0] Version:counter-1 PortID:wasm.juno1suhgf5svhu4usrurvxzlgn54ksxmn8gljarjtxqnapv8kjnp4nrsf8smqw ChannelID:channel-1} 
  {State:STATE_TRYOPEN Ordering:ORDER_UNORDERED Counterparty:{PortID:wasm.juno14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9skjuwg8 ChannelID:channel-1} ConnectionHops:[connection-0] Version:counter-1 PortID:wasm.juno1suhgf5svhu4usrurvxzlgn54ksxmn8gljarjtxqnapv8kjnp4nrsf8smqw ChannelID:channel-2}
]
```

While the first 2 channels are correct, not only that the 3rd one shouldn't even be there or try to open, but its trying to open an invalid channel connection, it tries to map left chain `channel-1` to right chain `channel-2`, which doesn't make sense because left chain `channel-1` is already "taken" and it shouldn't try to do that.

Let me know if more details are needed.

**Comment by 0xekez** [comment]
hey @jonathanpberger, thanks for the response and bug fix :)

how does versioning work with interchaintest? we are [using the v4 branch](https://github.com/strangelove-ventures/interchaintest/issues/424#issuecomment-1465521991) so will our tests automatically pick up this relayer fix?

**Comment by Reecepbcups** [comment]
@0xekez You can use a custom docker image for the relayer like so

```
"github.com/strangelove-ventures/interchaintest/v4/relayer"
"github.com/strangelove-ventures/interchaintest/v4/relayer/rly"

r := interchaintest.NewBuiltinRelayerFactory(
		ibc.CosmosRly,
		zaptest.NewLogger(t),
		relayer.CustomDockerImage("ghcr.io/cosmos/relayer", "v2.3.0-rc3", rly.RlyDefaultUidGid),
	).Build(t, client, network)
	```

**Comment by Art3miX** [comment]
Thanks @Reecepbcups for this workaround! very useful.

But I think the underlined question still stands, how maintained v4 is? and will fixes be shipped to it as well?

**Comment by jonathanpberger** [comment]
Closing ticket. Future-proofing work will continue in #488
