### ISSUE TITLE
Trying to test client misbehavior (frozen state)

### ISSUE THREAD

**Issue by Art3miX** [strangelove-ventures/interchaintest#478]
Hey, im trying to write a test to see how a frozen client behave, basically trying to mimic this test from ibc-go: https://github.com/cosmos/ibc-go/blob/main/e2e/tests/core/client_test.go#L142

Here is my try: https://github.com/Art3miX/cw-ibc-example/blob/art/malicious-tests/tests/strangelove/malicious_frozen_client_test.go#L159

The ibc-go test is working with a simapp, but we want to do it with interchainTest, is it even possible to duplicate this test?

The "funny" part is where I get stuck at, if im using Juno chains and trying to broadcast the malicious TX, it says that its expecting a `cosmos` prefix instead of `juno` prefix, from looking at the code, its seems like the prefix check happens on a static config that contains `cosmos` as the prefix, and theres no way of changing it.

Im new to go testing, so it might be some stupid mistake on my part, but would love for any pointers I can get!

**Comment by jtieri** [comment]
Hey @Art3miX! I actually just recently implemented a misbheaviour test case using `interchaintest` in the go-relayer if you wanna check that out [here](https://github.com/cosmos/relayer/blob/f9aaf3dd0ebfe99fbe98d190a145861d7df93804/interchaintest/misbehaviour_test.go#L38)

re: the prefix issue, this is a major pain point in the SDK that has slowly become the bane of my existence. I think we work around this in `interchaintest` so if you are leaning on the API that the framework provides it shouldn't be an issue. If you are calling into the SDK directly that's where it starts to present itself. We have a pattern for working around this that we adopted in the relayer https://github.com/cosmos/relayer/blob/f9aaf3dd0ebfe99fbe98d190a145861d7df93804/relayer/chains/cosmos/bech32_hack.go#L11-L23

**Comment by Art3miX** [comment]
Thanks a lot @jtieri, at least I see its possible and im not that far off, you using gaia so it works, but it juno still expects cosmos prefix ..., i am using the v4, which might not have this hack? 

Any hint on how I can use `SetSDKContext`? do I just use it in the start of the test and it just works like magic?

**Comment by jtieri** [comment]
No problem, I actually just edited that test case to use juno v13.0.0 and it seems to still pass!

To use that `SetSDKContext` function you would call it before signing the tx, sign the tx, and then invoke the `Lock` function that `SetSDKContext` returns

Ex: https://github.com/cosmos/relayer/blob/f9aaf3dd0ebfe99fbe98d190a145861d7df93804/relayer/chains/cosmos/tx.go#L379-L390

**Comment by Art3miX** [comment]
Amazing!!! thank you so much for your help!
