### ISSUE TITLE
Polkadot faucet amount not expected

### ISSUE THREAD

**Issue by anhductn2001** [strangelove-ventures/interchaintest#512]
I have a problem with interchain-test after merge feat/hyperspace. Now faucet amount in polkadot not expected.
I will provide some info here:
- Test file : https://github.com/notional-labs/composable-testnet/pull/22/files#diff-aaedc72ac1a2215732ceed25f5e539f4fb366424d069770815e9dd80b8dfac1e
- This test work normally before merged (In v7 main)
![image](https://user-images.githubusercontent.com/62016666/233895728-7cc8010b-0c8a-42e8-8027-14ec82b880ec.png)

**Comment by misko9** [comment]
PR above should fix your issue. I'll merge it in once it is reviewed. With polkadot's additional scaling that we have, due to their 12 decimal precision, our faucet amount was large enough to overflow int64.

**Comment by anhductn2001** [comment]
Yes, @misko9. I followed examples. Update example would probably be great.
