### ISSUE TITLE
Conformance test does not support localhost client

### ISSUE THREAD

**Issue by migueldingli1997** [strangelove-ventures/interchaintest#670]
The current conformance test sets up a connection on a pair of chains and checks that [only one connection exists](https://github.com/strangelove-ventures/interchaintest/blob/cedf87f4624d3b65b1684632aa11adb3cb84358d/conformance/relayersetup.go#L94-L101) (i.e. only one was created). As of newer versions of ibc-go, chains now have the localhost connection as well, which is [created at genesis](https://github.com/cosmos/ibc-go/blob/v7.2.0/modules/core/03-connection/genesis.go#L23). This causes the one connection check to fail.

**Comment by gjermundgaraba** [comment]
Supported in rly 2.4.0: https://github.com/cosmos/relayer/releases/tag/v2.4.0
