### ISSUE TITLE
Cut branch for: sdk `v0.50.0` and ibc-go `v8`

### ISSUE THREAD

**Issue by boojamya** [strangelove-ventures/interchaintest#676]
IBC-Go alpha: https://github.com/cosmos/ibc-go/tree/upgrade-sdk-v0.50-alpha1

**Comment by faddat** [comment]
Thanks for getting that PR merged!

I've made this:


https://github.com/cosmos/ibc-go/pull/4578

The intention is to update the module paths for ibc in interchaintest right after https://github.com/cosmos/ibc-go/pull/4578 is merged, so I'll have a PR in for that today.

**Comment by boojamya** [comment]
https://github.com/strangelove-ventures/interchaintest/pull/716
