### ISSUE TITLE
Bring back `wasm`, `polkadot` and `hyperspace` upon support

### ISSUE THREAD

**Issue by boojamya** [strangelove-ventures/interchaintest#723]
This issue is specific to this branch: https://github.com/notional-labs/interchaintest/tree/faddat/sdk-50-v2 (soon to be merged to main)

These modules were removed in this PR because they lacked support for sdk 50. 
https://github.com/strangelove-ventures/interchaintest/pull/716

The commits were clean. 
Upon sdk 50 support, we should be able to do a `git revert <COMMIT>`

```[tasklist]
### Tasks
- [ ] wasm
- [x] polkadot
- [x] hyperspace
```

**Comment by akc2267** [comment]
polkadot and hyperspace started, wasm blocked until wasmd supports v50 - @akc2267 to follow up with confio
