### ISSUE TITLE
Refactor `UsingNewGenesisCommand`

### ISSUE THREAD

**Issue by boojamya** [strangelove-ventures/interchaintest#742]
Specifically for the `SDK 50`, this is not new anymore and is actually the default.

We should change this to be something like `UsingLegacyGenesisCommand`

**Comment by Reecepbcups** [comment]
Other option is to entirely remove this and use HasCommand (for pre-setup with the faucet account). Then at run time start we can query the RPC and get what SDK version it is (45, 47+).
