### ISSUE TITLE
Remove complex example test

### ISSUE THREAD

**Issue by Reecepbcups** [strangelove-ventures/interchaintest#794]
Only applies to test which have examples in other repos (ex IBC-Apps) then linking in a .md (See [comment](https://github.com/strangelove-ventures/interchaintest/pull/678#pullrequestreview-1640104648))

We still need to ensure all interface methods are tested, just not duplicated (We dont need 3 example test ensuring IBC transfers work, just 1 which shows the example. Then linking to Juno, Noble, IBC-Apps, etc for other instances)

benefits:
- less flakey test
- less to maintain for unrelated testing
- faster e2e

**Comment by jackzampolin** [comment]
looks good to me! As long as I have a single place (The examples readme I would assume) where I can point people looking to learn more about interchain test I'm good
