### ISSUE TITLE
More ICA examples & utilities

### ISSUE THREAD

**Issue by Reecepbcups** [strangelove-ventures/interchaintest#807]
We should have more examples for how to use interchain-accounts (outside examples are good). Then condense redundant functions where applicable for common workflows

Also validate we have support in our other language drivers
- [ ] Rust
- [ ] Python

**Comment by srdtrk** [comment]
Here is an example. This is an ica controller written in pure cosmwasm. And its e2e test is written using interchaintest already https://github.com/srdtrk/cw-ica-controller/

**Comment by Reecepbcups** [comment]
dupe of: #14 - closing
