### ISSUE TITLE
Implement CometMock (opt-in)

### ISSUE THREAD

**Issue by Reecepbcups** [strangelove-ventures/interchaintest#824]
https://github.com/informalsystems/CometMock

- [x] Depends on: https://github.com/cosmos/cosmos-sdk/pull/18110. Need to update ICtest to this commit so gas sim & hermes works
- [ ] design spec / impl. PR as an opt-in for a network. 
    - 1 docker instance per chain-id / network
- [ ] Move our internal test over to it

**Comment by Reecepbcups** [comment]
#291 May be useful here to separate the TM client from the node itself. Also could ref Penumbra's impl since it uses 2 different binaries

**Comment by akc2267** [comment]
blocked on github CI

**Comment by jonathanpberger** [comment]
Unblocked. Now just waiting for a PR review.
