### ISSUE TITLE
Add Ethermint chain support to v7 / v6

### ISSUE THREAD

**Issue by ItayLevyOfficial** [strangelove-ventures/interchaintest#835]
I am trying to utilize the tests with my cosmos-sdk chain, but it can't start it. It fails with 
```
?panic: validator set is empty after InitGenesis, please ensure at least one validator is initialized with a delegation greater than or equal to the DefaultPowerReduction 
```

What may it be? My current chain config is 
```
[]*interchaintest.ChainSpec{
		{Name: "dymension", Version: "latest", ChainConfig: ibc.ChainConfig{
			Type:           "cosmos",
			ChainID:        "dymension_100-1",
			Images:         []ibc.DockerImage{{Repository: "dymension", UidGid: "1025:1025"}},
			Bin:            "dymd",
			Bech32Prefix:   "dym",
			Denom:          "udym",
			CoinType:       "60",
			GasPrices:      "0udym",
			GasAdjustment:  0,
			TrustingPeriod: "168h0m0s",
		}},
		{Name: "osmosis", Version: "v7.2.0", ChainConfig: ibc.ChainConfig{ChainID: "osmosis-1001"}},
	}
```

Dymension fails, osmosis works.

**Comment by ItayLevyOfficial** [comment]
Hey! Thanks for reaching back to me. I don't think this is the problem, as I am pointing to a local docker image and it is being fetched successfully. The problem happens when the test try to start the container chain, which throws the error I have been written below: `?panic: validator set is empty after InitGenesis, please ensure at least one validator is initialized with a delegation greater than or equal to the DefaultPowerReduction`

**Comment by ItayLevyOfficial** [comment]
Are you familiar with this error by any chance?

**Comment by Reecepbcups** [comment]
@ItayLevyOfficial Gotcha - could you make it `[]ibc.DockerImage{{Repository: "dymension", Version: "latest", UidGid: "1025:1025"}},`

(make sure version is `latest` and not `local`. Some will build as `dymension:local`)

if this does not fix it, please send me your entire log via a pastebin (or gist) and I will dive in further

**Comment by ItayLevyOfficial** [comment]
Hey! I've made the changes, but the error persists. I believe I've pinpointed the issue. Our chain, "Dymension," utilizes 18 token decimals, while the default in Cosmos is 6. We adopted 18 decimals for compatibility with Ethereum. The validator delegation specified by interchaintest in the genesis configuration is 5000000000000, likely assuming 6 decimals. This amount is beneath the hardcoded minimum delegation in our chain's code. Do you know if there's a straightforward way to adjust the chain's decimal settings?

**Comment by ItayLevyOfficial** [comment]
Apparently there is a `ModifyGenesisAmounts` parameter to modify those, I will try and see if it solves the issue

**Comment by Reecepbcups** [comment]
@ItayLevyOfficial I just checked and interchaintest does not yet have ethermint support. This should become easier to add after the Avalance support PR is added. But for now due to the use of hex addresses, I am unsure if interchaintest can handle this properly.

**Comment by ItayLevyOfficial** [comment]
Ye. Also the genesis amounts are limited to less then 10 tokens as long as you use 18 decimals due to [this](https://github.com/strangelove-ventures/interchaintest/blob/10163eed3185004a37602b49b887c2e5d7e16d66/chain/cosmos/chain_node.go#L657) line. Is there an open issue on this? We want to utilize your framework for our chain to test our IBC connection with dymension rollapps.

**Comment by jtieri** [comment]
I started utilizing the sdk's `Int` type, which is a wrapper around `big.Int`, in a few places some months ago to get support for Penumbra off the ground since they use `int128` iirc. I'm not sure if there is an open issue for the limitation that you have pointed out but I personally am not opposed to the proliferation of the `sdk.Int` type throughout the framework given we have a few chains in the pipeline who need support for values greater than what a 64bit integer can represent. 

#679

**Comment by Reecepbcups** [comment]
Completed. Ethermint support is added in the main branch

**Comment by ItayLevyOfficial** [comment]
Hey, thanks for the update. When trying to upgrade the dependency and run my test I get ```itaylevy@Itays-MacBook-Pro dymension_interchaintest % go test ./...
# github.com/cosmos/cosmos-sdk/types
../../.gvm/pkgsets/go1.21.0/global/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.0-rc.1.0.20231026141021-0469fc17e158/types/context.go:64:29: undefined: comet.BlockInfo
../../.gvm/pkgsets/go1.21.0/global/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.0-rc.1.0.20231026141021-0469fc17e158/types/context.go:91:36: undefined: comet.BlockInfo
../../.gvm/pkgsets/go1.21.0/global/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.0-rc.1.0.20231026141021-0469fc17e158/types/context.go:299:48: undefined: comet.BlockInfo
FAIL	dymension_interchaintest [build failed]
FAIL
itaylevy@Itays-MacBook-Pro dymension_interchaintest ```
Are you familiar with with this error? @Reecepbcups

**Comment by Reecepbcups** [comment]
@ItayLevyOfficial Were you using the v7 branch before? Can you share me a gist / pastebin of your code? I did not run into this issue in my test on build

**Comment by ItayLevyOfficial** [comment]
Nop, v8. I just copied the `learn_ibc_test.go` file to a new repo i created and I try to make it work with our chain. You can take a look here --> https://github.com/dymensionxyz/dymension_interchaintest/tree/itay-games

**Comment by ItayLevyOfficial** [comment]
I looked a bit more into this – you have `github.com/cosmos/cosmos-sdk v0.50.0-rc.1.0.20231026141021-0469fc17e158` as a dependency in interchaintest, and this version doesn't compile. There is a closed issue on it [here](https://github.com/cosmos/cosmos-sdk/issues/17950), but there hasn't been a new release with a fix yet. Do you have any idea how I can get my code to compile?

**Comment by Reecepbcups** [comment]
@ItayLevyOfficial can you confirm if the latest ictest main commit solves this for you? (sdk v0.50.1, seems the have had many issues tagging upstream)

if not, replacing the cosmossdk.io/core => v0.11.0 in your go.mod should resolve it

**Comment by ItayLevyOfficial** [comment]
Confirmed. Thanks a lot buddy!

**Comment by ItayLevyOfficial** [comment]
Now I am getting this error 
```
Error: error creating clients: failed to create client on src chain{dymension_100-1}: failed to send messages on chain{dymension_100-1}: no concrete type registered for type URL /ethermint.types.v1.EthAccount against interface *types.AccountI
```

When trying 

```
	require.NoError(t, ic.Build(ctx, eRep, interchaintest.InterchainBuildOptions{
		TestName:  t.Name(),
		Client:    client,
		NetworkID: network,
		// BlockDatabaseFile: interchaintest.DefaultBlockDatabaseFilepath(),

		SkipPathCreation: false},
	),
	)
```

Do you have any idea why this may happen?

**Comment by Reecepbcups** [comment]
@ItayLevyOfficial You need to register the ethermint Interface type(s) for your test since Ethermint is it's own Module.

ibc.ChainConfig example: https://github.com/CosmosContracts/juno/blob/main/interchaintest/setup.go#L81-L110

**Comment by ItayLevyOfficial** [comment]
Tried to run `go get github.com/evmos/evmos/v12/crypto/codec` to get the Ethermint interface types but got
```
go: dymension_interchaintest tested by
	dymension_interchaintest.test imports
	github.com/evmos/evmos/v12/crypto/codec imports
	github.com/evmos/evmos/v12/crypto/ethsecp256k1 imports
	github.com/evmos/evmos/v12/ethereum/eip712 imports
	github.com/cosmos/cosmos-sdk/simapp/params: github.com/cosmos/cosmos-sdk/simapp@v0.0.0-20231116110448-e534c4a42324: parsing go.mod:
	module declares its path as: cosmossdk.io/simapp
	        but was required as: github.com/cosmos/cosmos-sdk/simapp
```

Do you know how it can be solved? I think this is because evmos is using a different cosmos-sdk version

**Comment by Reecepbcups** [comment]
@ItayLevyOfficial likely due to changes in v8 vs v7. I need to see if we can backport math.Int to v7 branch since ethermint is not using that hmm

**Comment by ItayLevyOfficial** [comment]
Cool ping me when there's an update on this

**Comment by ItayLevyOfficial** [comment]
Can you re-open this issue pls?

**Comment by Reecepbcups** [comment]
Ahh, looks like Ethermint on SDK v46 is causing some problems in relation to all imports. The `v7` branch is SDK 47, which uses the new `cosmossdk.io/` namespace instead of `github.com/cosmos/cosmos-sdk/simapp`. This has cascading effects through IBC-Go, Tendermint/CometBFT, Ethermint, and the Cosmos-SDK.

So it looks like this has to be ported to the `v6` interchaintest branch instead of `v7` as originally hoped.

**Comment by Reecepbcups** [comment]
@ItayLevyOfficial I have the interchaintest case passing now for evmos
![image](https://github.com/strangelove-ventures/interchaintest/assets/31943163/9f2af99b-61fd-404e-97d9-b1200121a2d0)

Currently I use a slightly modified relayer (to register the extra ethermint codec for accounts) but will be modifying this in interchaintest to allow for standard relayers :)

**Comment by ItayLevyOfficial** [comment]
Thanks a lot man!
