### ISSUE TITLE
Requirements from Quasar team

### ISSUE THREAD

**Issue by jackzampolin** [strangelove-ventures/interchaintest#84]
# Multi-chain setup

At this moment, the test framework setup takes a pair of chains (source and destination chains).
This is enough most of the times but becomes a blocker for more complex scenarios.

An example involving 3 chains (A, B, C): an IBC denom, originally from ChainA, needs to be transferred from ChainB to ChainC. The ChainA needs to be used as pass-through using the packet-forwarder feature so that the denon is valid in the destination ChainC.

Ideally, the `ibc-test-framework` should take an arbitrary number of blockchains as an input for the test setup.
All chains will be started, same as now, and it is for the developer to orchestrate the communication between these chains and test accordingly.

Note that we could also imagine future scenarios where multiple relayers are needed.

## Changes

The main change is in the test setup.

`ibctest/test_setup.go`

```golang
func StartChainsAndRelayerFromFactory(
	t *testing.T,
	ctx context.Context,
	pool *dockertest.Pool,
	networkID string,
	home string,
	srcChain, dstChain ibc.Chain,
	f RelayerFactory,
	preRelayerStart func([]ibc.ChannelOutput, User, User) error,
) (ibc.Relayer, []ibc.ChannelOutput, *User, *User, error)
```

It currently takes two chains but should accept an arbitrary number, or a wrapping structure containing the various chains to be started.

# Interchain Accounts support

The Interchain accounts feature is currently missing in the `ibc-test-framework`. Only the `SendIBCTransfer` is available on the `type Chain interface`.

The test framework should allow the developer to configure their ICA keepers accordingly and access the connections IDs necessary to start sending ICA packets.

## Changes

A way to access the IBC connection IDs is needed to send ICA packets.
A new `IBCConnection` structure could be introduced containing more than what is currently in the `ChannelOutput`.
The appropriate genesis params will have to be set on the host chain (like the `allow_list` for the ICA messages).

# Other

- Ability to use locally built docker image

**Comment by jtieri** [comment]
Implemented some of the pieces for testing interchain accounts in #103

**Comment by jtieri** [comment]
We have a working Interchain Accounts test example here: https://github.com/strangelove-ventures/ibctest/pull/117
Support for interchain accounts in the main branch of the relayer will likely not land until we undergo the `ChainProcessor` refactor; progress can be tracked here https://github.com/cosmos/relayer/milestone/6

I also started to piece together a test utilizing the packet forward middleware. This one is not yet complete but it's in this branch if anyone is interested https://github.com/strangelove-ventures/ibctest/commit/eddb7e62bf7ea01af5042188c73558f184485691
