### ISSUE TITLE
Add support for `UpdateClient` to hyperspace relayer abstraction

### ISSUE THREAD

**Issue by damiannolan** [strangelove-ventures/interchaintest#863]
## Summary / Feature Request

Add support for ibc client updates using the hyperspace relayer implementation.

Essentially, implement this:
https://github.com/strangelove-ventures/interchaintest/blob/main/relayer/hyperspace/hyperspace_commander.go#L224-L226

**Comment by damiannolan** [comment]
I assume the hyperspace relayer must have client update functionality built in somehow as there is already successful happy path transfer tests using cosmos chains <-> polkadot. I'm guessing that it is just not directly exposed via a CLI?

**Comment by jonathanpberger** [comment]
Doesn't look like there's an `update client` command exposed in the CLI. When that's added upstream, we'll revisit.

In the meantime, here's what's exposed: https://github.com/ComposableFi/composable-ibc/blob/master/hyperspace/README.md#running-hyperspace---cli-interface

**Comment by damiannolan** [comment]
Thanks, I'll open an issue upstream as well 👍

**Comment by Reecepbcups** [comment]
Once upstream adds it we are happy to add it in. Closing since it is out of our control for the time being.
