### ISSUE TITLE
(v7) make functions and packages public

### ISSUE THREAD

**Issue by Reecepbcups** [strangelove-ventures/interchaintest#869]
Since this is a framework for testing, we should attempt to make all functions (within reason) public.

# Versions
- [ ] v7
- [x] v8 (main)

- ex: `PrivValFileContent` and `OverwritePrivValFile` in v7.

this may also be useful with the `internal/` repo. For example, the local-interchain lense clone could use docker internal functions, but it can not be accessed outside.

**Comment by chatton** [comment]
Was just going to create an issue to make some of the functions in the internal package public, specifically the `FileRetriever` type and associated functions, fetching files (such as private keys) from validator nodes can be extremely useful in some more complex test scenarios.

**Comment by Reecepbcups** [comment]
still have to do v7

**Comment by Reecepbcups** [comment]
Compelted
