### ISSUE TITLE
Add parameter allows Docker Setup without cleanup in special cases

### ISSUE THREAD

**Issue by anhductn2001** [strangelove-ventures/interchaintest#903]
For example, in this case of [ibc-go](https://github.com/cosmos/ibc-go/pull/5317), we want to run e2e in each suite using only 1 container chain and relayer from start to finish.

Func Suggestion:
```
func DockerSetup(t DockerSetupTestingT, cleanUp bool) (*client.Client, string) {
	t.Helper()
	cli, err := client.NewClientWithOpts(client.FromEnv)
	if err != nil {
		panic(fmt.Errorf("failed to create docker client: %v", err))
	}
        if cleanUp {
		// Clean up docker resources at end of test.
	        t.Cleanup(dockerCleanup(t, cli))

	        // Also eagerly clean up any leftover resources from a previous test run,
	        // e.g. if the test was interrupted.
	        dockerCleanup(t, cli)()
	}

	name := fmt.Sprintf("interchaintest-%s", RandLowerCaseLetterString(8))
	network, err := cli.NetworkCreate(context.TODO(), name, types.NetworkCreate{
		CheckDuplicate: true,
		Labels: map[string]string{CleanupLabel: t.Name()},
	})
	if err != nil {
		panic(fmt.Errorf("failed to create docker network: %v", err))
	}
	return cli, network.ID
}
```

**Comment by Reecepbcups** [comment]
Our env options can be found [here](https://github.com/strangelove-ventures/interchaintest/blob/main/docs/envOptions.md). This includes a `KEEP_CONTAINERS=true` to keep the containers alive and prevent testnet cleanup after completion.

Does this fit your need?

**Comment by anhductn2001** [comment]
I will try it, is there any example of its usage?

**Comment by anhductn2001** [comment]
OMG! I'm sure it's not working yet, we have a typo [here](https://github.com/strangelove-ventures/interchaintest/blob/2f014d308bea4429169c94c4ba08759ce5e7be03/internal/dockerutil/setup.go#L96C48-L96C48).

**Comment by Reecepbcups** [comment]
Good catch, will get a fix in for this now.

KEEP_CONTAINTERS=true will work for now then

**Comment by anhductn2001** [comment]
Thanks @Reecepbcups
