### ISSUE TITLE
Errors in cosmos Broadcaster are sometimes are not propagated to caller

### ISSUE THREAD

**Issue by chatton** [strangelove-ventures/interchaintest#937]
When working on a test, I noticed the following behaviour when calling [BroadcastTx](https://github.com/strangelove-ventures/interchaintest/blob/66cb76406407fbc931486165d4c8f257ff86b9bb/chain/cosmos/broadcaster.go#L188).

The response returned [here](https://github.com/strangelove-ventures/interchaintest/blob/66cb76406407fbc931486165d4c8f257ff86b9bb/chain/cosmos/broadcaster.go#L222) did not error, but included an error message in the `RawLogs` of the response.

The error in question I believe happened in the `ValidateBasic` of a message that was broadcast.

I think in the case of `RawLogs` being populated on the linked line, we can return an error with the contents (even though the actual `err` returned is nil ).

The happy path here is that all fields except for `txHash` should be zero values.

cc @crodriguezvega

**Comment by Reecepbcups** [comment]
ref: https://github.com/strangelove-ventures/interchaintest/pull/842
