### ISSUE TITLE
The Cosmos Relayer creates a localhost client even if `SkipPathCreation: true`

### ISSUE THREAD

**Issue by boojamya** [strangelove-ventures/interchaintest#966]
If you set `SkipPathCreation: true` and  you run `GetClients` after building the interchain, there is a `09-localhost` client. 

If this is a feature and not a bug, Close this!

**Comment by srdtrk** [comment]
This is automatically created by ibc-go during genesis. So it is not up to the relayers

**Comment by boojamya** [comment]
Ah, thank your for the context.
Closing!
