### ISSUE TITLE
SendIBCTransfer bug with sequence numbers larger than max int

### ISSUE THREAD

**Issue by KyleMoser** [strangelove-ventures/interchaintest#977]
In interchaintest/chain/cosmos/cosmos_chain.go `SendIBCTransfer` , there appears to be a bug...

```
seqNum, err := strconv.Atoi(seq)
    if err != nil {
        return tx, fmt.Errorf("invalid packet sequence from events %s: %w", seq, err)
    }
    tx.Packet.Sequence = uint64(seqNum)
```

Defined in ICS-4, sequences are int64 type. The call to `strconv.Atoi` treats it as an int type. It should use `strconv.ParseInt(seq, 10, 64)`.

**Comment by pharr117** [comment]
@KyleMoser I see this definition of Packet in ICS-4:

https://github.com/cosmos/ibc/blob/ded4eb44d8c6b4d32d386728414bec3999fa069a/spec/core/ics-004-channel-and-packet-semantics/README.md?plain=1#L119-L128

Sequence looks like a uint64 in the above, so I believe we should be parsing with ParseUint64. Its also being cast to uint64 after parsing and during assignment to `tx.Packet.Sequence`. Please let me know if I am wrong.
