### ISSUE TITLE
Wasm IBC test ought not fail.

### ISSUE THREAD

**Issue by peterblockman** [strangelove-ventures/interchaintest#998]
I ran TestWasmIbc on the main branch and got this error: "Error:  Should NOT be empty, but was"
```
                Error Trace:   /Projects/test/interchaintest/examples/ibc/wasm/wasm_ibc_test.go:173
                Error:          Should NOT be empty, but was 
                Test:           TestWasmIbc
```
looks like it failed to reflect the account on juno2

full log: 
[ibc_test_log.txt](https://github.com/strangelove-ventures/interchaintest/files/14417648/ibc_test_log.txt)

**Comment by Reecepbcups** [comment]
Thank you for the report! I will be taking a look into why this is occurring and moving it to our main testing CI suite to ensure it does not happen again

**Comment by jonathanpberger** [comment]
Calling in the CosmWasm calvary @kakucodes
